### PR TITLE
Added tests to spring-boot-orientdb-shiro sample.

### PR DESCRIPTION
**Pull request by pires**
The project build now depends on `spring-boot-orientdb-shiro` sample tests.

### CODE REVIEW

**Comment by lvca** [comment]
We found OrientDB not compatible with Hazelcast 3.5. Did you try it?

**Comment by pires** [comment]
@lvca yes. I would never open the PR if it didn't built. Again, this is against 2.0.x and not 2.1.x because of #26.

**Comment by pires** [comment]
```
$ mvn -q clean test

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: TestNG652Configurator
14:18:31.154 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Could not instantiate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [javax/servlet/ServletContext]
14:18:31.160 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@11c20519, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@70beb599, org.springframework.test.context.support.DirtiesContextTestExecutionListener@4e41089d]
14:18:31.166 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Could not instantiate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [javax/servlet/ServletContext]
14:18:31.166 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@4148db48, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@282003e1, org.springframework.test.context.support.DirtiesContextTestExecutionListener@7fad8c79]
14:18:31.173 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@11e21d0e]
14:18:31.178 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Could not instantiate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [javax/servlet/ServletContext]
14:18:31.179 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@31206beb, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@3e77a1ed, org.springframework.test.context.support.DirtiesContextTestExecutionListener@3ffcd140]
14:18:31.379 [pool-1-thread-1] INFO  o.s.c.s.GenericApplicationContext - Refreshing org.springframework.context.support.GenericApplicationContext@683e9776: startup date [Fri Aug 07 14:18:31 WEST 2015]; root of context hierarchy
14:18:32.273 [pool-1-thread-1] INFO  com.orientechnologies - OrientDB auto-config DISKCACHE=10,695MB (heap=3,641MB os=16,384MB disk=401,381MB)
14:18:33.483 [pool-1-thread-1] INFO  org.jooq.Constants -

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.6.2

14:18:33.590 [pool-1-thread-1] INFO  o.s.c.s.GenericApplicationContext - Closing org.springframework.context.support.GenericApplicationContext@683e9776: startup date [Fri Aug 07 14:18:31 WEST 2015]; root of context hierarchy
14:18:33.595 [pool-1-thread-1] INFO  o.s.c.s.GenericApplicationContext - Refreshing org.springframework.context.support.GenericApplicationContext@453ea488: startup date [Fri Aug 07 14:18:33 WEST 2015]; root of context hierarchy
Tests run: 38, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.461 sec - in TestSuite
14:18:34.038 [Thread-7] INFO  o.s.c.s.GenericApplicationContext - Closing org.springframework.context.support.GenericApplicationContext@453ea488: startup date [Fri Aug 07 14:18:33 WEST 2015]; root of context hierarchy

Results :




Tests run: 38, Failures: 0, Errors: 0, Skipped: 0


-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.springframework.boot.orient.sample.shiro.rest.UserControllerTest
Configuring TestNG with: TestNG652Configurator
2015-08-07 14:18:39.010  INFO   --- [           main] o.s.t.c.web.WebTestContextBootstrapper   : Using TestExecutionListeners: [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@4450d156]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.5.RELEASE)

2015-08-07 14:18:39.386  INFO 7752 --- [pool-1-thread-1] o.s.b.o.s.shiro.rest.UserControllerTest  : Starting UserControllerTest on littlepires.local with PID 7752 (/Users/pires/Work/Projects/spring-data-orientdb/spring-data-orientdb-samples/spring-boot-orientdb-shiro/target/test-classes started by pires in /Users/pires/Work/Projects/spring-data-orientdb/spring-data-orientdb-samples/spring-boot-orientdb-shiro)
2015-08-07 14:18:39.637  INFO 7752 --- [pool-1-thread-1] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4f4d03ec: startup date [Fri Aug 07 14:18:39 WEST 2015]; root of context hierarchy
2015-08-07 14:18:40.430  INFO 7752 --- [pool-1-thread-1] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2015-08-07 14:18:40.710  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'shiroConfiguration' of type [class org.springframework.boot.orient.sample.shiro.ShiroConfiguration$$EnhancerBySpringCGLIB$$6e07b77d] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:40.892  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'passwordService' of type [class org.apache.shiro.authc.credential.DefaultPasswordService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:40.897  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'credentialsMatcher' of type [class org.apache.shiro.authc.credential.PasswordMatcher] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:40.975  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'spring.data.orient.CONFIGURATION_PROPERTIES' of type [class org.springframework.boot.autoconfigure.orient.OrientProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:40.977  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.orient.OrientAutoConfiguration' of type [class org.springframework.boot.autoconfigure.orient.OrientAutoConfiguration$$EnhancerBySpringCGLIB$$c742d690] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:41.721  INFO 7752 --- [pool-1-thread-1] com.orientechnologies                    : OrientDB auto-config DISKCACHE=10,695MB (heap=3,641MB os=16,384MB disk=401,380MB)
2015-08-07 14:18:42.363  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'objectDatabaseFactory' of type [class org.springframework.data.orient.object.OrientObjectDatabaseFactory] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.382  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'objectTemplate' of type [class org.springframework.data.orient.object.OrientObjectTemplate] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.388  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean '(inner bean)#31bbcdcd' of type [class org.springframework.beans.factory.config.PropertiesFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.389  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean '(inner bean)#31bbcdcd' of type [class java.util.Properties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.394  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean '(inner bean)#7b42d9b6' of type [class org.springframework.data.repository.core.support.PropertiesBasedNamedQueries] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.401  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean '(inner bean)#7dad5eb7' of type [class org.springframework.data.repository.query.ExtensionAwareEvaluationContextProvider] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.512  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'userRepository' of type [class org.springframework.data.orient.object.repository.support.OrientObjectRepositoryFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.514  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'userRepository' of type [class com.sun.proxy.$Proxy57] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.519 DEBUG 7752 --- [pool-1-thread-1] o.a.s.spring.LifecycleBeanPostProcessor  : Initializing bean [realm]...
2015-08-07 14:18:42.519 DEBUG 7752 --- [pool-1-thread-1] org.apache.shiro.realm.AuthorizingRealm  : No authorizationCache instance set.  Checking for a cacheManager...
2015-08-07 14:18:42.519  INFO 7752 --- [pool-1-thread-1] org.apache.shiro.realm.AuthorizingRealm  : No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2015-08-07 14:18:42.519  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'realm' of type [class org.springframework.boot.orient.sample.shiro.shiro.OrientDbRealm] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:42.553  INFO 7752 --- [pool-1-thread-1] o.s.b.o.s.s.shiro.HazelcastSessionDao    : Initializing Hazelcast Shiro session persistence..
2015-08-07 14:18:42.632  INFO 7752 --- [pool-1-thread-1] c.h.instance.DefaultAddressPicker        : [LOCAL] [hc] [3.5.1] Prefer IPv4 stack is true.
2015-08-07 14:18:42.682  INFO 7752 --- [pool-1-thread-1] c.h.instance.DefaultAddressPicker        : [LOCAL] [hc] [3.5.1] Picked Address[192.168.1.103]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
2015-08-07 14:18:42.915  INFO 7752 --- [pool-1-thread-1] com.hazelcast.spi.OperationService       : [192.168.1.103]:5701 [hc] [3.5.1] Backpressure is disabled
2015-08-07 14:18:42.928  INFO 7752 --- [pool-1-thread-1] c.h.s.i.o.c.ClassicOperationExecutor     : [192.168.1.103]:5701 [hc] [3.5.1] Starting with 2 generic operation threads and 4 partition operation threads.
2015-08-07 14:18:43.309  INFO 7752 --- [pool-1-thread-1] com.hazelcast.system                     : [192.168.1.103]:5701 [hc] [3.5.1] Hazelcast 3.5.1 (20150727 - 795ce7d) starting at Address[192.168.1.103]:5701
2015-08-07 14:18:43.309  INFO 7752 --- [pool-1-thread-1] com.hazelcast.system                     : [192.168.1.103]:5701 [hc] [3.5.1] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
2015-08-07 14:18:43.317  INFO 7752 --- [pool-1-thread-1] com.hazelcast.instance.Node              : [192.168.1.103]:5701 [hc] [3.5.1] Creating MulticastJoiner
2015-08-07 14:18:43.320  INFO 7752 --- [pool-1-thread-1] com.hazelcast.core.LifecycleService      : [192.168.1.103]:5701 [hc] [3.5.1] Address[192.168.1.103]:5701 is STARTING
2015-08-07 14:18:45.756  INFO 7752 --- [pool-1-thread-1] c.h.cluster.impl.MulticastJoiner         : [192.168.1.103]:5701 [hc] [3.5.1]


Members [1] {
	Member [192.168.1.103]:5701 this
}

2015-08-07 14:18:45.790  INFO 7752 --- [pool-1-thread-1] com.hazelcast.core.LifecycleService      : [192.168.1.103]:5701 [hc] [3.5.1] Address[192.168.1.103]:5701 is STARTED
2015-08-07 14:18:45.851  INFO 7752 --- [pool-1-thread-1] o.s.b.o.s.s.shiro.HazelcastSessionDao    : Hazelcast Shiro session persistence initialized.
2015-08-07 14:18:45.856  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'sessionDao' of type [class org.springframework.boot.orient.sample.shiro.shiro.HazelcastSessionDao] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:45.869  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'sessionManager' of type [class org.apache.shiro.web.session.mgt.DefaultWebSessionManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:45.892  INFO 7752 --- [pool-1-thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'securityManager' of type [class org.apache.shiro.web.mgt.DefaultWebSecurityManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-08-07 14:18:46.169  INFO 7752 --- [pool-1-thread-1] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2015-08-07 14:18:46.495  INFO 7752 --- [pool-1-thread-1] o.apache.catalina.core.StandardService   : Starting service Tomcat
2015-08-07 14:18:46.497  INFO 7752 --- [pool-1-thread-1] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.23
2015-08-07 14:18:46.663  INFO 7752 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2015-08-07 14:18:46.664  INFO 7752 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 7031 ms
2015-08-07 14:18:46.785 DEBUG 7752 --- [ost-startStop-1] o.a.s.spring.web.ShiroFilterFactoryBean  : Creating Shiro Filter instance.
2015-08-07 14:18:46.824 DEBUG 7752 --- [ost-startStop-1] o.a.s.spring.web.ShiroFilterFactoryBean  : Found filter chain candidate filter 'hiddenHttpMethodFilter'
2015-08-07 14:18:46.847 DEBUG 7752 --- [ost-startStop-1] o.a.s.spring.web.ShiroFilterFactoryBean  : Found filter chain candidate filter 'characterEncodingFilter'
2015-08-07 14:18:47.318  INFO 7752 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2015-08-07 14:18:47.323  INFO 7752 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2015-08-07 14:18:47.324  INFO 7752 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2015-08-07 14:18:47.325  INFO 7752 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'shiroFilter' to: [/*]
2015-08-07 14:18:47.517 DEBUG 7752 --- [pool-1-thread-1] o.a.s.spring.LifecycleBeanPostProcessor  : Initializing bean [orientDbRealm]...
2015-08-07 14:18:47.518 DEBUG 7752 --- [pool-1-thread-1] org.apache.shiro.realm.AuthorizingRealm  : No authorizationCache instance set.  Checking for a cacheManager...
2015-08-07 14:18:47.518  INFO 7752 --- [pool-1-thread-1] org.apache.shiro.realm.AuthorizingRealm  : No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2015-08-07 14:18:47.742  INFO 7752 --- [pool-1-thread-1] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4f4d03ec: startup date [Fri Aug 07 14:18:39 WEST 2015]; root of context hierarchy
2015-08-07 14:18:47.846  INFO 7752 --- [pool-1-thread-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/users],methods=[GET]}" onto public java.util.List<org.springframework.boot.orient.sample.shiro.model.User> org.springframework.boot.orient.sample.shiro.rest.UserController.getAll()
2015-08-07 14:18:47.848  INFO 7752 --- [pool-1-thread-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/users/do_something],methods=[GET]}" onto public java.util.List<org.springframework.boot.orient.sample.shiro.model.User> org.springframework.boot.orient.sample.shiro.rest.UserController.dontHavePermission()
2015-08-07 14:18:47.851  INFO 7752 --- [pool-1-thread-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/users],methods=[PUT]}" onto public void org.springframework.boot.orient.sample.shiro.rest.UserController.initScenario()
2015-08-07 14:18:47.851  INFO 7752 --- [pool-1-thread-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/users/auth],methods=[POST]}" onto public void org.springframework.boot.orient.sample.shiro.rest.UserController.authenticate(org.apache.shiro.authc.UsernamePasswordToken)
2015-08-07 14:18:47.854  INFO 7752 --- [pool-1-thread-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2015-08-07 14:18:47.854  INFO 7752 --- [pool-1-thread-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest)
2015-08-07 14:18:47.889  INFO 7752 --- [pool-1-thread-1] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-08-07 14:18:47.890  INFO 7752 --- [pool-1-thread-1] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-08-07 14:18:47.917  INFO 7752 --- [pool-1-thread-1] .m.m.a.ExceptionHandlerExceptionResolver : Detected @ExceptionHandler methods in applicationExceptionHandler
2015-08-07 14:18:47.943  INFO 7752 --- [pool-1-thread-1] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-08-07 14:18:48.118  INFO 7752 --- [pool-1-thread-1] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2015-08-07 14:18:48.124  INFO 7752 --- [pool-1-thread-1] o.s.b.o.s.shiro.rest.UserControllerTest  : Started UserControllerTest in 8.965 seconds (JVM running for 9.883)
2015-08-07 14:18:48.493  INFO 7752 --- [pool-1-thread-1] org.jooq.Constants                       :

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.6.2

{"username":"pjpires@gmail.com","password":"wrong password","rememberMe":false,"host":null,"principal":"pjpires@gmail.com","credentials":"wrong password"}
2015-08-07 14:18:49.027  INFO 7752 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2015-08-07 14:18:49.027  INFO 7752 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2015-08-07 14:18:49.047  INFO 7752 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 20 ms
2015-08-07 14:18:49.071 DEBUG 7752 --- [nio-8080-exec-1] a.s.s.m.AbstractValidatingSessionManager : No sessionValidationScheduler set.  Attempting to create default instance.
2015-08-07 14:18:49.075  INFO 7752 --- [nio-8080-exec-1] a.s.s.m.AbstractValidatingSessionManager : Enabling session validation scheduler...
2015-08-07 14:18:49.077 DEBUG 7752 --- [nio-8080-exec-1] o.a.s.session.mgt.DefaultSessionManager  : Unable to resolve session ID from SessionKey [org.apache.shiro.web.session.mgt.WebSessionKey@721118b9].  Returning null to indicate a session could not be found.
2015-08-07 14:18:49.363  INFO 7752 --- [nio-8080-exec-1] o.s.b.o.s.shiro.rest.UserController      : Authenticating pjpires@gmail.com with password [w, r, o, n, g,  , p, a, s, s, w, o, r, d]
2015-08-07 14:18:49.386 DEBUG 7752 --- [nio-8080-exec-1] o.a.shiro.realm.AuthenticatingRealm      : Looked up AuthenticationInfo [pjpires@gmail.com] from doGetAuthenticationInfo
2015-08-07 14:18:49.387 DEBUG 7752 --- [nio-8080-exec-1] o.a.shiro.realm.AuthenticatingRealm      : AuthenticationInfo caching is disabled for info [pjpires@gmail.com].  Submitted token: [org.apache.shiro.authc.UsernamePasswordToken - pjpires@gmail.com, rememberMe=false].
2015-08-07 14:18:49.637 DEBUG 7752 --- [nio-8080-exec-1] o.apache.shiro.web.servlet.SimpleCookie  : Added HttpServletResponse Cookie [rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 06-Aug-2015 13:18:49 GMT]
2015-08-07 14:18:49.640  WARN 7752 --- [nio-8080-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Handler execution resulted in exception: Submitted credentials for token [org.apache.shiro.authc.UsernamePasswordToken - pjpires@gmail.com, rememberMe=false] did not match the expected credentials.
{"username":"pjpires@gmail.com","password":"123qwe","rememberMe":false,"host":null,"principal":"pjpires@gmail.com","credentials":"123qwe"}
2015-08-07 14:18:49.660 DEBUG 7752 --- [nio-8080-exec-3] o.a.s.session.mgt.DefaultSessionManager  : Unable to resolve session ID from SessionKey [org.apache.shiro.web.session.mgt.WebSessionKey@62931e8e].  Returning null to indicate a session could not be found.
2015-08-07 14:18:49.662  INFO 7752 --- [nio-8080-exec-3] o.s.b.o.s.shiro.rest.UserController      : Authenticating pjpires@gmail.com with password [1, 2, 3, q, w, e]
2015-08-07 14:18:49.666 DEBUG 7752 --- [nio-8080-exec-3] o.a.shiro.realm.AuthenticatingRealm      : Looked up AuthenticationInfo [pjpires@gmail.com] from doGetAuthenticationInfo
2015-08-07 14:18:49.667 DEBUG 7752 --- [nio-8080-exec-3] o.a.shiro.realm.AuthenticatingRealm      : AuthenticationInfo caching is disabled for info [pjpires@gmail.com].  Submitted token: [org.apache.shiro.authc.UsernamePasswordToken - pjpires@gmail.com, rememberMe=false].
2015-08-07 14:18:49.877 DEBUG 7752 --- [nio-8080-exec-3] o.a.shiro.authc.AbstractAuthenticator    : Authentication successful for token [org.apache.shiro.authc.UsernamePasswordToken - pjpires@gmail.com, rememberMe=false].  Returned account [pjpires@gmail.com]
2015-08-07 14:18:49.878 DEBUG 7752 --- [nio-8080-exec-3] o.a.s.s.support.DefaultSubjectContext    : No SecurityManager available in subject context map.  Falling back to SecurityUtils.getSecurityManager() lookup.
2015-08-07 14:18:49.878 DEBUG 7752 --- [nio-8080-exec-3] o.a.s.s.support.DefaultSubjectContext    : No SecurityManager available in subject context map.  Falling back to SecurityUtils.getSecurityManager() lookup.
2015-08-07 14:18:49.880 DEBUG 7752 --- [nio-8080-exec-3] o.a.s.session.mgt.DefaultSessionManager  : Creating new EIS record for new session instance [org.apache.shiro.session.mgt.SimpleSession,id=null]
2015-08-07 14:18:49.886  INFO 7752 --- [nio-8080-exec-3] c.h.partition.InternalPartitionService   : [192.168.1.103]:5701 [hc] [3.5.1] Initializing cluster partition table first arrangement...
2015-08-07 14:18:49.908 DEBUG 7752 --- [nio-8080-exec-3] o.apache.shiro.web.servlet.SimpleCookie  : Added HttpServletResponse Cookie [JSESSIONID=6ca2d804-95d6-403f-bfc0-ffccf2c2d445; Path=/; HttpOnly]
2015-08-07 14:18:49.919 DEBUG 7752 --- [nio-8080-exec-3] o.apache.shiro.web.servlet.SimpleCookie  : Added HttpServletResponse Cookie [rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 06-Aug-2015 13:18:49 GMT]
2015-08-07 14:18:49.919 DEBUG 7752 --- [nio-8080-exec-3] o.a.shiro.mgt.AbstractRememberMeManager  : AuthenticationToken did not indicate RememberMe is requested.  RememberMe functionality will not be executed for corresponding account.
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.594 sec - in org.springframework.boot.orient.sample.shiro.rest.UserControllerTest
2015-08-07 14:18:50.013  INFO 7752 --- [       Thread-1] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4f4d03ec: startup date [Fri Aug 07 14:18:39 WEST 2015]; root of context hierarchy
2015-08-07 14:18:50.020 DEBUG 7752 --- [       Thread-1] o.a.s.spring.LifecycleBeanPostProcessor  : Destroying bean [securityManager]...
2015-08-07 14:18:50.021  INFO 7752 --- [       Thread-1] a.s.s.m.AbstractValidatingSessionManager : Disabled session validation scheduler.
2015-08-07 14:18:50.022 DEBUG 7752 --- [       Thread-1] o.a.s.spring.LifecycleBeanPostProcessor  : Destroying bean [sessionManager]...

Results :




Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by lvca** [comment]
Ok, that test doesn't use OrientDB cluster. I'd prefer to leave the same HZ version in OrientDB repo to avoid conflicts. WDYT?

**Comment by pires** [comment]
@lvca downgraded to 3.3.5 as requested.

**Comment by lvca** [comment]
Cool, thanks.

**Pull request merged**
