### PR TITLE
Issue #17: Package scanner for entity classes

### PR DESCRIPTION
**Pull request by saljuama**
Created the `@OEntity` annotation to annotate classes that are meant to be entities, and be able to scan them.

Then created the `OrientPackageScanner` with 2 public methods, to be able to process the `@EnableOrientRepositories` properties `basePackages` and `basePackageClasses`.

Haven't created any unit test, because honestly, don't know how to mock a classpath with made up classes, but tested it locally and it manages to finds all the classes annotated with it, and any class that extends it (even if it doesn't have the annotation).

### CODE REVIEW

**Comment by lvca** [comment]
Why don't use the @Entity annotation?

http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.misc.entity-scanning

**Comment by saljuama** [comment]
I've thought of using **@Entity** in the first place, but then thinking of the GraphAPI, where you can define custom Edge types, made me realize that a mechanism to differentate **Vertex** entities from **Edge** entities in some way should be taken into consideration. This is why i discarded using the existing **@Entity**, and included **@OEntity** to include such mechanism in the future.

**Comment by saljuama** [comment]
Now using `@Entity ` annotation. Since it wasn't on the classpath, had to add the dependency in the `pom.xml` file.

Also added a couple of unit tests.

**Comment by lvca** [comment]
@saljuama Sorry for the delay, I received tons of notification from GitHub in the last period. I like @Entity better, or another approach could be using something like @Vertex and @Edge. I'm going to merge this, but I'm open to consider using of vertex/edge annotation if you think it's a good idea. Thanks for this PR.

**Pull request merged**
