### PR TITLE
Cleanup - squid:S1312 - Loggers should be "private static final" and …

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S1312 - Loggers should be "private static final" and should share a naming convention

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1312

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by lvca** [comment]
Could you please send the PR to the develop (last development branch)?

**Comment by m-ezzat** [comment]
I found that the develop branch doesn't have these issues

**Comment by lvca** [comment]
So somebody already fix it?

**Comment by m-ezzat** [comment]
yep

**Pull request closed without merging**
